//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborArtifact) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborArtifact"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborArtifactList) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborArtifactList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborArtifactStatus) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborArtifactStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborRepository) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborRepository"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborRepositoryList) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborRepositoryList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborRepositoryStatus) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborRepositoryStatus"
}
