//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborArtifact) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborArtifact"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborArtifactList) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborArtifactList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborArtifactReference) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborArtifactReference"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborArtifactStatus) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborArtifactStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborPlatform) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborPlatform"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborReplication) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborReplication"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborReplicationExecution) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborReplicationExecution"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborReplicationList) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborReplicationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborReplicationSpec) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborReplicationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborReplicationStatus) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborReplicationStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborRepository) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborRepository"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborRepositoryList) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborRepositoryList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborRepositoryStatus) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborRepositoryStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarborTag) OpenAPIModelName() string {
	return "io.goharbor.harbor.v1alpha1.HarborTag"
}
