## Scope

This is a personal fork.  Do not file issues or PRs against any other repos.


## Attribution of GitHub posts

Anything posted to GitHub from a Claude session appears under the repository
owner's account. Every issue, issue comment, pull request description,
review, and review comment that Claude writes must begin with the line

    🤖 Created by Claude 🤖

as its first line, before any other text. This applies without exception,
including edits of earlier posts.

## Testing

Default to red/green TDD for most work: write a failing test first, then
the minimum code to make it pass.

If I were to mutate or remove the production code, then a test ought to fail!


## Writing style
This applies to code comments, commit messages, issues, markdown docs, etc.
- Write as little as possible.  Clean code and tests should be largely self-documenting through variable and function names.
  Aggressively remove prose that doesn't add significant value beyond the code itself.
- Prune historical context that isn't immediately necessary to understand current behavior.
- Prefer short, complete sentences with a clear subject and verb.  A noun phrase is not a sentence.


## Adversarial review

For any nontrivial work, before claiming to be done, spawn at least one
subagent to do an "adversarial review" and address its findings.

Here are some possible reviewer personas to use, depending on context:
- A kubernetes maintainer, familiar with ecosystem conventions
- An exploratory tester, who tries to use the software (not just reading code) and looks for surprising behavior
- A senior engineer who will be maintaining the code going forward.  They value clean, self-documenting code and meaningful tests.
  They also demand clear, minimal prose and enforce the writing style rules above.


## Editing this file

Do not edit this file without checking with the user first.
