apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.harbor.goharbor.io
spec:
  group: harbor.goharbor.io
  version: v1alpha1
  groupPriorityMinimum: 1000
  versionPriority: 15
  # deploy/cert-manager or hack/gen-serving-cert.sh sets caBundle.
  service:
    name: harbor-apiserver
    namespace: harbor-apiserver
    port: 443
