apiVersion: v1
kind: Service
metadata:
  name: harbor-apiserver
  namespace: harbor-apiserver
spec:
  selector:
    app: harbor-apiserver
  ports:
    - name: https
      port: 443
      targetPort: https
